# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Tadoba by Jaiveer Talwar"
subtitle: "2021"
author:  "Jaiveer Talwar"
header:
 title: "Tadoba"
 subtitle: "by Jaiveer Talwar"
footer:
 name: "Tadoba, Maharastra, India "
 bio: "Tigers, Leopards and more"
social_urls:
  twitter: "https://twitter.com"
  instagram: "https://www.instagram.com/"
  linkedin: "https://www.linkedin.com/"
  github: "https://github.com/jaiveertalwar"

theme: jekyll-theme-slate